packages:
  - packages/*

injectWorkspacePackages: true

# 2 days, in minutes
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - mutation-testing-elements
  - mutation-testing-metrics
  - mutation-testing-report-schema

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/endpoint'
  - chokidar
  - semver

onlyBuiltDependencies:
  - '@nestjs/core'
  - azure-functions-core-tools
  - nx

ignoredBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver
