packages:
  - packages/*

injectWorkspacePackages: true

# 2 days, in minutes
minimumReleaseAge: 2880

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/endpoint'
  - chokidar
  - semver
  - undici

onlyBuiltDependencies:
  - '@nestjs/core'
  - azure-functions-core-tools
  - esbuild
  - nx

ignoredBuiltDependencies:
  - protobufjs
  - unrs-resolver
minimumReleaseAgeExclude:
  # Renovate security update: ajv@8.18.0
  - ajv@8.18.0
