packages:
  - packages/*

# 2 days, in minutes
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - mutation-testing-elements
  - mutation-testing-metrics
  - mutation-testing-report-schema

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/endpoint'
  - chokidar
  - semver
allowBuilds:
  '@nestjs/core': true
  azure-functions-core-tools: false
  nx: true
  esbuild: false
  protobufjs: false
  unrs-resolver: false
