packages:
  - packages/*

injectWorkspacePackages: true

# 2 days, in minutes
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - mutation-testing-elements
  - mutation-testing-metrics
  - mutation-testing-report-schema
  # Renovate security update: vite@8.0.5
  - vite@8.0.5

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/endpoint'
  - chokidar
  - semver
allowBuilds:
  '@nestjs/core': true
  azure-functions-core-tools: true
  nx: true
  esbuild: false
  protobufjs: false
  unrs-resolver: false
