name: 'Deploy to Production'

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  release:
    name: 'Build and Release'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./.github/setup

      - name: Build
        run: pnpm run build

      - name: Lerna publish
        run: pnpm lerna publish from-git --yes

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            strykermutator/dashboard
            ghcr.io/stryker-mutator/dashboard

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          push: true
          build-args: 'version=${{ steps.meta.outputs.version }}'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Package badge-api
        run: pnpm badge-api --node-linker=hoisted deploy --prod package

      - name: Upload badge-api package artifact
        uses: actions/upload-artifact@v5
        with:
          name: badge-api-package
          path: package

  deploy-dashboard:
    name: 'Deploy Dashboard'
    runs-on: ubuntu-latest
    needs: release
    environment:
      name: Production
      url: https://dashboard.stryker-mutator.io
    concurrency:
      group: Production Dashboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: 'Login via Azure CLI'
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_IDENTITY_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_IDENTITY_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_IDENTITY_SUBSCRIPTION_ID }}

      - name: 'Deploy dashboard.stryker-mutator.io'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stryker-badge'
          images: 'ghcr.io/stryker-mutator/dashboard:latest'

      - name: 'Verify deployment'
        run: node tasks/check-version dashboard https://dashboard.stryker-mutator.io/api/version ${{ needs.release.outputs.version}}

  deploy-badge-api:
    name: 'Deploy badge-api.stryker-mutator.io'
    runs-on: ubuntu-latest
    needs: release
    environment: Production
    concurrency:
      group: Production Badge Api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: 'Login via Azure CLI'
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_IDENTITY_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_IDENTITY_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_IDENTITY_SUBSCRIPTION_ID }}

      - name: Download badge-api package artifact
        uses: actions/download-artifact@v6
        with:
          name: badge-api-package
          path: package

      - name: 'Deploy badge-api.stryker-mutator.io'
        uses: Azure/functions-action@v1
        with:
          app-name: stryker-mutator-badge-api
          package: 'package'

      - name: 'Verify deployment'
        run: node tasks/check-version badge-api https://badge-api.stryker-mutator.io/api/ ${{ needs.release.outputs.version }}
