name: 'Deploy to Production'

on:
  release:
    types: [created]

jobs:
  release:
    name: 'Build and Release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set NPM Env
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lerna publish
      run: npx lerna publish from-git --yes --no-verify-access
    - name: Docker build & Tag
      run: | # Add a sleep to give npmjs.com the time to get the versions consistent 
        sleep 30s
        cd docker
        NPM_PACKAGE_VERSION=${GITHUB_REF:11}
        docker build -t strykermutator/dashboard:${NPM_PACKAGE_VERSION} -t strykermutator/dashboard:latest --build-arg version=${NPM_PACKAGE_VERSION} .
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker push strykermutator/dashboard:${NPM_PACKAGE_VERSION}
        docker push strykermutator/dashboard:latest

  deploy-dashboard:
    name: 'Deploy Dashboard'
    runs-on: ubuntu-latest
    needs: release
    environment: Production
    concurrency: Production Dashboard
    steps:
    - uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DASHBOARD_PRODUCTION }}
    - name: 'Deploy dashboard.stryker-mutator.io'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stryker-badge'
        images: 'strykermutator/dashboard:latest'
    - name: 'Verify deployment'
      run: node tasks/check-version dashboard https://dashboard.stryker-mutator.io/api/version ${GITHUB_REF:11}

  deploy-badge-api:
    name: 'Deploy badge-api.stryker-mutator.io'
    runs-on: ubuntu-latest
    needs: release
    environment: Production
    concurrency: Production Badge Api
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
    - name: 'Download & prepare badge-api package'
      run: ./tasks/download-badge-api-package.sh ${GITHUB_REF:11}
    - name: 'Deploy badge-api.stryker-mutator.io'
      uses: Azure/functions-action@v1.5.1
      id: fa
      with:
        app-name: stryker-mutator-badge-api
        package: 'package'
    - name: 'Verify deployment'
      run: node tasks/check-version badge-api https://badge-api.stryker-mutator.io/api/ ${GITHUB_REF:11}
