on:
  workflow_call:
    inputs:
      is-latest:
        required: true
        type: boolean
      version:
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - run: |
          echo "Releasing version ${{ inputs.version }} (is-latest: ${{ inputs.is-latest }})"

      - name: Publish latest
        if: ${{ inputs.is-latest == true }}
        run: npx lerna publish from-git --yes

      - name: Publish canary version
        if: ${{ inputs.is-latest == false }}
        run: |
          git config --global user.name "stryker-mutator[bot]"
          git config --global user.email 158062761+stryker-mutator[bot]@users.noreply.github.com
          npx lerna version ${{ inputs.version }} --no-git-tag-version --no-push --exact --force-publish --yes --no-conventional-commits
          git commit -am "temp-commit"
          npx lerna publish from-package --dist-tag canary --no-git-reset --yes

      - name: Wait for package to be available
        run: node tasks/wait-for-npm-package.js ${{ inputs.version }}
